services:
  - type: web
    name: pulsestop
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build && ls -la dist && cd server && npm install express socket.io cors
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production