services:
  - type: web
    name: pulsestop
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production