services:
  - type: web
    name: pulsestop
    runtime: node
    plan: free
    buildCommand: >-
      set -e && \
      npm install && \
      npm run build && \
      rm -rf server/public && mkdir -p server/public && \
      cp -R dist/* server/public/ && \
      cd server && npm install --omit=dev
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production