services:
  - type: web
    name: stop-game-fullstack
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000