services:
  - type: web
    name: pulsestop
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build && rm -rf server/public && mkdir -p server/public && cp -r dist/* server/public/ && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production