services:
  - type: web
    name: stop-game-server
    runtime: node
    plan: free
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
  - type: web
    name: stop-game-frontend
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000