services:
  # Fullstack Service (Frontend + Backend)
  - type: web
    name: pulsestop
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build && cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production